<a href="https://colab.research.google.com/github/JhobanyT/Unidad2-S1-GuiaPracticaNumPy/blob/main/Gu%C3%ADa_Pr%C3%A1ctica_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

# **Importar Numpy**

In [62]:
import numpy as np

# **1. Creación de Arrays**

In [63]:
# 1. Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
arreglo = np.array([6,7,8,9,10])
print('Arreglo de una dimensión:\n',arreglo)

Arreglo de una dimensión:
 [ 6  7  8  9 10]


In [64]:
# 2. Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
matriz_bidimensional = np.arange(1, 10).reshape(3, 3)
print('Matriz bidimensional:\n',matriz_bidimensional)

Matriz bidimensional:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
# 3. Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
matriz_ceros = np.zeros((2,4),int)
print('Tabla con valores ceros:\n',matriz_ceros)

Tabla con valores ceros:
 [[0 0 0 0]
 [0 0 0 0]]


In [66]:
# 4. Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
matriz_unos = np.ones((3,2),int)
print('Tabla con valores unos:\n',matriz_unos)

Tabla con valores unos:
 [[1 1]
 [1 1]
 [1 1]]


In [67]:
# 5. Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.
matriz_random_1_10 = np.random.randint(0, 11, size=(4, 4))
print('Tabla con valores Random del 0 al 10:\n',matriz_random_1_10)

Tabla con valores Random del 0 al 10:
 [[10 10  0  1]
 [ 5  1 10  4]
 [ 1  9  7  9]
 [ 1  6  8  5]]


# **2. Acceso a Elementos**

In [68]:
# 1. Accede al tercer elemento del vector creado en el paso 1.
tercer_elemento_arreglo = arreglo[2]
print("El tercer elemento del vector 1 es: ", tercer_elemento_arreglo)

El tercer elemento del vector 1 es:  8


In [69]:
# 2. Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2.
elemento_fila2_columna2 = matriz_bidimensional[1, 1]
print('Elemento en la segunda fila y segunda columna:', elemento_fila2_columna2)

Elemento en la segunda fila y segunda columna: 5


# **3. Propiedades de los Arrays**

In [70]:
# 1. Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.
print('El arreglo tiene:',matriz_bidimensional.ndim, "dimensiones")

El arreglo tiene: 2 dimensiones


In [71]:
# 2. Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
print('Número de filas y columnas de la matriz bimensional:',matriz_bidimensional.shape)

Número de filas y columnas de la matriz bimensional: (3, 3)


In [72]:
# 3. Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.
print('los elementos de la matriz bidimensional son:',matriz_bidimensional.size)

los elementos de la matriz bidimensional son: 9


# **4. Operaciones Básicas**

In [73]:
# 1. Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
matriz_1 = np.random.randint(0, 11, (2, 2))
matriz_2 = np.random.randint(0, 11, (2, 2))
suma = matriz_1 + matriz_2
print("La suma de las dos matrices es:\n", suma)

La suma de las dos matrices es:
 [[ 8 13]
 [17 11]]


In [74]:
# 2. Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
matriz_3 = np.random.randint(0, 11, (3, 2))
matriz_4 = np.random.randint(0, 11, (2, 3))
multiplicacion = np.dot(matriz_3, matriz_4)
print("La multiplicación de las dos matrices es:\n", multiplicacion)

La multiplicación de las dos matrices es:
 [[ 50 100  90]
 [ 10  26  30]
 [ 20  70  96]]


In [75]:
# 3. Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2,
# utilizando tanto la división por elementos como la multiplicación por la inversa.

matriz_5 = np.random.randint(1, 11, (2, 2))
matriz_6 = np.random.randint(1, 11, (2, 2))

print('Matriz E:\n', matriz_5)
print('Matriz F:\n', matriz_6,'\n')

# División por elementos
division_elementos = matriz_5 / matriz_6
print('División por elementos:\n', division_elementos,'\n')

# Multiplicación por la inversa
inversa_matriz_f = np.linalg.inv(matriz_6)
multiplicacion_inversa = np.matmul(matriz_5, inversa_matriz_f)
print('Multiplicación por la inversa:\n', multiplicacion_inversa)

Matriz E:
 [[7 4]
 [3 7]]
Matriz F:
 [[5 8]
 [1 8]] 

División por elementos:
 [[1.4   0.5  ]
 [3.    0.875]] 

Multiplicación por la inversa:
 [[ 1.625   -1.125  ]
 [ 0.53125  0.34375]]


# **5. Manipulación de Arrays**

In [76]:
# 1. Utiliza la función reshape() para convertir el vector creado en el paso 2 en una matriz de tamaño 9x1.
matriz_9x1 = matriz_bidimensional.reshape(9, 1)
print('Matriz 9x1:\n', matriz_9x1)

Matriz 9x1:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [77]:
# 2. Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.
vector_unidimensional = matriz_bidimensional.flatten()
print('Vector unidimensional:\n', vector_unidimensional)

Vector unidimensional:
 [1 2 3 4 5 6 7 8 9]


# **6. Operaciones Estadísticas**

In [78]:
# 1. Calcula la suma de todos los elementos de la matriz creada en el paso 2.
suma_total = np.sum(matriz_bidimensional)
print('La suma de todos los elementos de la matriz es:', suma_total)

La suma de todos los elementos de la matriz es: 45


In [79]:
# 2. Calcula la media de cada fila de la matriz creada en el paso 2.
media_por_fila = np.mean(matriz_bidimensional, axis=1)
print('La media de cada fila de la matriz es:', media_por_fila)

La media de cada fila de la matriz es: [2. 5. 8.]


# **7. Indexación y Rebanado**

In [84]:
# 1. Imprime la primera fila de la matriz creada en el paso 2.
primera_fila = matriz_bidimensional[0]
print('Primera fila de la matriz:', primera_fila)

Primera fila de la matriz: [1 2 3]


In [85]:
# 2. Imprime las primeras dos columnas de la matriz creada en el paso 2.
primeras_dos_columnas = matriz_bidimensional[:, :2]
print('Primeras dos columnas de la matriz:\n', primeras_dos_columnas)

Primeras dos columnas de la matriz:
 [[1 2]
 [4 5]
 [7 8]]


# **8. Ejercicio Adicional**

In [86]:
# 1. efine una matriz de tamaño 4x4 con valores aleatorios.
matriz_aleatoria = np.random.rand(4, 4)
print('Matriz aleatoria 4x4:\n', matriz_aleatoria)

Matriz aleatoria 4x4:
 [[0.74396161 0.16943888 0.04050581 0.24384907]
 [0.40933519 0.41918824 0.44954569 0.58937373]
 [0.68000462 0.58783226 0.92426179 0.21748164]
 [0.11985204 0.49336033 0.90283421 0.64932719]]


In [87]:
# 2. Escribe un código para encontrar el valor máximo y mínimo de la matriz, así como su posición.

# Encontrar el valor máximo y su posición
max_valor = np.max(matriz_aleatoria)
max_posicion = np.argmax(matriz_aleatoria)
max_posicion_fila = max_posicion // matriz_aleatoria.shape[1]  # Calcular la fila
max_posicion_columna = max_posicion % matriz_aleatoria.shape[1]  # Calcular la columna

print('Valor máximo:', max_valor)
print('Posición del valor máximo (fila, columna):', (max_posicion_fila, max_posicion_columna))

# Encontrar el valor mínimo y su posición
min_valor = np.min(matriz_aleatoria)
min_posicion = np.argmin(matriz_aleatoria)
min_posicion_fila = min_posicion // matriz_aleatoria.shape[1]  # Calcular la fila
min_posicion_columna = min_posicion % matriz_aleatoria.shape[1]  # Calcular la columna

print('Valor mínimo:', min_valor)
print('Posición del valor mínimo (fila, columna):', (min_posicion_fila, min_posicion_columna))

Valor máximo: 0.9242617933539763
Posición del valor máximo (fila, columna): (2, 2)
Valor mínimo: 0.040505805257062044
Posición del valor mínimo (fila, columna): (0, 2)
